# Generated by Django 5.1 on 2025-03-19 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fingerprint_data', models.TextField()),
                ('retina_data', models.TextField()),
                ('is_registered', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='voter_images/')),
                ('address', models.TextField(blank=True, null=True)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhaar_num', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar number must be 12 digits.')])),
            ],
        ),
    ]
