# Generated by Django 5.1 on 2025-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='voted_users',
            field=models.ManyToManyField(blank=True, to='manager.voter'),
        ),
    ]
